import unittest

from vttformatter import VttFormatter

class TestVttFormatter(unittest.TestCase):

    def setUp( self ):
        self.formatter = VttFormatter( 'data/test_AutoGeneratedCaption.vtt' )

     
    def test_import_file( self ):
        with open('data/test_data_list.txt') as fp:
             test_data_list = fp.readlines()
        self.formatter.import_file()
        self.assertEqual( self.formatter.data, test_data_list )


